-- ============================================================
-- FS-2 Vendor Management System — Initial Schema
-- Migration: 001_init.sql
-- ============================================================

-- ─── Vendors table ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vendors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_name     TEXT NOT NULL CHECK (char_length(vendor_name) >= 2),
    company_name    TEXT NOT NULL,
    email_address   TEXT NOT NULL UNIQUE,
    contact_number  TEXT NOT NULL,
    business_address TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'Active'
                    CHECK (status IN ('Active', 'Inactive')),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ─── Quotations table ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS quotations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id           BIGINT REFERENCES vendors(id) ON DELETE CASCADE NOT NULL,
    quotation_title     TEXT NOT NULL,
    description         TEXT NOT NULL,
    vendor_reference    TEXT NOT NULL UNIQUE,
    quotation_amount    NUMERIC(12, 2) NOT NULL CHECK (quotation_amount > 0),
    submission_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    status              TEXT NOT NULL DEFAULT 'Pending'
                        CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ─── Activity log table ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS activity_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event       TEXT NOT NULL,
    message     TEXT NOT NULL,
    entity_id   BIGINT,
    metadata    JSONB DEFAULT '{}',
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ─── Performance indexes ────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_vendors_name_company
    ON vendors(vendor_name, company_name);

CREATE INDEX IF NOT EXISTS idx_vendors_status
    ON vendors(status);

CREATE INDEX IF NOT EXISTS idx_vendors_email
    ON vendors(email_address);

CREATE INDEX IF NOT EXISTS idx_quotations_vendor_id
    ON quotations(vendor_id);

CREATE INDEX IF NOT EXISTS idx_quotations_title
    ON quotations(quotation_title);

CREATE INDEX IF NOT EXISTS idx_quotations_status
    ON quotations(status);

CREATE INDEX IF NOT EXISTS idx_quotations_amount
    ON quotations(quotation_amount);

CREATE INDEX IF NOT EXISTS idx_quotations_submission_date
    ON quotations(submission_date);

CREATE INDEX IF NOT EXISTS idx_activity_log_created_at
    ON activity_log(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_log_event
    ON activity_log(event);
